### ISSUE TITLE
Does it work with 1.21.3?

### ISSUE THREAD

**Issue by msolli** [sdphantomz3/lifestealmod#18]
I installed the mod with 1.21.3, and got this stack trace in the log:

```
[10:25:35] [main/INFO]: Lifesteal mod has been initialized!
[10:25:35] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'lifestealmod' at 'com.phantomz3.LifestealMod'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.3-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1271
	at knot/com.phantomz3.LifestealMod.registerEvents(LifestealMod.java:180) ~[lifestealmod-2.0.jar:?]
	at knot/com.phantomz3.LifestealMod.onInitialize(LifestealMod.java:61) ~[lifestealmod-2.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1271
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
	at knot/com.phantomz3.LifestealMod.registerEvents(LifestealMod.java:180) ~[lifestealmod-2.0.jar:?]
	at knot/com.phantomz3.LifestealMod.onInitialize(LifestealMod.java:61) ~[lifestealmod-2.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	... 7 more
```

Is this due to the mod not being built for 1.21.3, or is there some other issue?

Thanks!

**Comment by sdphantomz3** [comment]
Currently the mod doesn't support 1.21.2 and above, I am working on a complete rework of this mod which will have support for 1.21. - 1.21.4 and it will be out in a couple of days.

**Comment by GazerBeamTwo** [comment]
Hey me and my friends are playing an SMP with your mod and we were wanting to update to 1.21.4 do you know when your going to be ready to update your mod?

**Comment by 81a7db** [comment]
You can clone and build it to work in 1.21.4 with some modifications to the code (all I remember is that TypedActionResult is replaced with ActionResult) if you are familiar with fabric modding. Otherwise, I can get one to you soon (~1week) if you want
