### ISSUE TITLE
unable to start server with mod installed

### ISSUE THREAD

**Issue by qwartzrat** [sdphantomz3/lifestealmod#8]
Crafty controller on ubuntu with fabric 1.21
log from start up

```
[12:19:49] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.0
[12:19:50] [main/INFO]: Loading 44 mods:
- fabric-api 0.102.1+1.21.1
|-- fabric-api-base 0.4.42+6573ed8c6a
|-- fabric-api-lookup-api-v1 1.6.68+b55973446a
|-- fabric-biome-api-v1 13.0.29+5bd9f1bc6a
|-- fabric-block-api-v1 1.0.22+0af3f5a76a
|-- fabric-block-view-api-v2 1.0.10+6573ed8c6a
|-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a76a
|-- fabric-client-tags-api-v1 1.1.15+6573ed8c6a
|-- fabric-command-api-v1 1.2.49+f71b366f6a
|-- fabric-command-api-v2 2.2.28+6ced4dd96a
|-- fabric-commands-v0 0.2.66+df3654b36a
|-- fabric-content-registries-v0 8.0.16+b55973446a
|-- fabric-convention-tags-v1 2.0.20+7f945d5b6a
|-- fabric-convention-tags-v2 2.6.0+605f22ad6a
|-- fabric-crash-report-info-v1 0.2.29+0af3f5a76a
|-- fabric-data-attachment-api-v1 1.1.27+1daea2156a
|-- fabric-data-generation-api-v1 20.2.17+16c4ae256a
|-- fabric-dimensions-v1 4.0.0+6fc22b996a
|-- fabric-entity-events-v1 1.6.12+6fc22b996a
|-- fabric-events-interaction-v0 0.7.12+ba9dae066a
|-- fabric-game-rule-api-v1 1.0.53+6ced4dd96a
|-- fabric-item-api-v1 11.0.0+afdfc9216a
|-- fabric-item-group-api-v1 4.1.4+780172706a
|-- fabric-key-binding-api-v1 1.0.47+0af3f5a76a
|-- fabric-keybindings-v0 0.2.45+df3654b36a
|-- fabric-lifecycle-events-v1 2.3.12+6c1df3606a
|-- fabric-loot-api-v2 3.0.14+3f89f5a56a
|-- fabric-loot-api-v3 1.0.2+3f89f5a56a
|-- fabric-message-api-v1 6.0.13+6573ed8c6a
|-- fabric-model-loading-api-v1 2.0.0+fe474d6b6a
|-- fabric-networking-api-v1 4.2.2+60c3209b6a
|-- fabric-object-builder-api-v1 15.2.0+40875a936a
|-- fabric-particles-v1 4.0.2+6573ed8c6a
|-- fabric-recipe-api-v1 5.0.12+650897126a
|-- fabric-registry-sync-v0 5.1.2+60c3209b6a
|-- fabric-renderer-api-v1 3.4.0+c705a49c6a
|-- fabric-renderer-indigo 1.7.0+c705a49c6a
|-- fabric-renderer-registries-v1 3.2.68+df3654b36a
|-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e6a
|-- fabric-rendering-fluids-v1 3.1.6+1daea2156a
|-- fabric-rendering-v0 1.1.71+df3654b36a
|-- fabric-rendering-v1 5.0.5+df16efd06a
|-- fabric-resource-conditions-api-v1 4.3.0+8dc279b16a
|-- fabric-resource-loader-v0 1.3.0+565991296a
|-- fabric-screen-api-v1 2.0.25+8b68f1c76a
|-- fabric-screen-handler-api-v1 1.3.86+b55973446a
|-- fabric-sound-api-v1 1.0.23+6573ed8c6a
|-- fabric-transfer-api-v1 5.1.17+1db1cc1f6a
\-- fabric-transitive-access-wideners-v1 6.1.0+1daea2156a
- fabricloader 0.16.0
\-- mixinextras 0.4.0
- java 21
- lifestealmod 1.3.2
- minecraft 1.21.1
- structory 1.3.5
- terralith 2.5.4
[12:19:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/crafty/servers/50a6f53e-11bc-432c-8a9f-308a07ff964c/libraries/net/fabricmc/sponge-mixin/0.15.0+mixin.0.8.7/sponge-mixin-0.15.0+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[12:19:50] [main/INFO]: Compatibility level set to JAVA_17
[12:19:50] [main/INFO]: Compatibility level set to JAVA_21
[12:19:50] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.0).
[12:19:58] [main/INFO]: Hello Fabric world!
[12:19:58] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'lifestealmod'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-1.21.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
at com.phantomz3.LifestealMod.registerConfig(LifestealMod.java:53) ~[lifestealmod-1.3.2.jar:?]
at com.phantomz3.LifestealMod.onInitialize(LifestealMod.java:46) ~[lifestealmod-1.3.2.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
... 7 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
at com.phantomz3.LifestealMod.registerConfig(LifestealMod.java:53) ~[lifestealmod-1.3.2.jar:?]
at com.phantomz3.LifestealMod.onInitialize(LifestealMod.java:46) ~[lifestealmod-1.3.2.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
... 7 more
```

**Comment by sdphantomz3** [comment]
This mod requires [`cloth-config`](https://modrinth.com/mod/cloth-config) as a required dependency.

**Comment by sdphantomz3** [comment]
If it still doesn't start let me know.

**Comment by sdphantomz3** [comment]
Closed due to inactivity.
